#%RAML 1.0
title: CoinStatsAPI
version: V1

/getrate/{asset_id}:
  get:
    description: get coin rates
    responses:
      200:
        body:
          application/json:
            example: !include Examples/response.json
              
    